// <auto-generated />
#pragma warning disable CS0105
using Master.Tables.Enemy;
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using System.Collections.Generic;
using System;

namespace App.MD.Tables
{
   public sealed partial class EnemySkillSetTable : TableBase<EnemySkillSetEntity>, ITableUniqueValidate
   {
        public Func<EnemySkillSetEntity, (uint SkillSetId, uint SkillId)> PrimaryKeySelector => primaryIndexSelector;
        readonly Func<EnemySkillSetEntity, (uint SkillSetId, uint SkillId)> primaryIndexSelector;

        readonly EnemySkillSetEntity[] secondaryIndex0;
        readonly Func<EnemySkillSetEntity, uint> secondaryIndex0Selector;

        public EnemySkillSetTable(EnemySkillSetEntity[] sortedData)
            : base(sortedData)
        {
            this.primaryIndexSelector = x => (x.SkillSetId, x.SkillId);
            this.secondaryIndex0Selector = x => x.SkillSetId;
            this.secondaryIndex0 = CloneAndSortBy(this.secondaryIndex0Selector, System.Collections.Generic.Comparer<uint>.Default);
            OnAfterConstruct();
        }

        partial void OnAfterConstruct();

        public RangeView<EnemySkillSetEntity> SortBySkillSetId => new RangeView<EnemySkillSetEntity>(secondaryIndex0, 0, secondaryIndex0.Length - 1, true);

        public EnemySkillSetEntity FindBySkillSetIdAndSkillId((uint SkillSetId, uint SkillId) key)
        {
            return FindUniqueCore(data, primaryIndexSelector, System.Collections.Generic.Comparer<(uint SkillSetId, uint SkillId)>.Default, key, true);
        }
        
        public bool TryFindBySkillSetIdAndSkillId((uint SkillSetId, uint SkillId) key, out EnemySkillSetEntity result)
        {
            return TryFindUniqueCore(data, primaryIndexSelector, System.Collections.Generic.Comparer<(uint SkillSetId, uint SkillId)>.Default, key, out result);
        }

        public EnemySkillSetEntity FindClosestBySkillSetIdAndSkillId((uint SkillSetId, uint SkillId) key, bool selectLower = true)
        {
            return FindUniqueClosestCore(data, primaryIndexSelector, System.Collections.Generic.Comparer<(uint SkillSetId, uint SkillId)>.Default, key, selectLower);
        }

        public RangeView<EnemySkillSetEntity> FindRangeBySkillSetIdAndSkillId((uint SkillSetId, uint SkillId) min, (uint SkillSetId, uint SkillId) max, bool ascendant = true)
        {
            return FindUniqueRangeCore(data, primaryIndexSelector, System.Collections.Generic.Comparer<(uint SkillSetId, uint SkillId)>.Default, min, max, ascendant);
        }

        public RangeView<EnemySkillSetEntity> FindBySkillSetId(uint key)
        {
            return FindManyCore(secondaryIndex0, secondaryIndex0Selector, System.Collections.Generic.Comparer<uint>.Default, key);
        }

        public RangeView<EnemySkillSetEntity> FindClosestBySkillSetId(uint key, bool selectLower = true)
        {
            return FindManyClosestCore(secondaryIndex0, secondaryIndex0Selector, System.Collections.Generic.Comparer<uint>.Default, key, selectLower);
        }

        public RangeView<EnemySkillSetEntity> FindRangeBySkillSetId(uint min, uint max, bool ascendant = true)
        {
            return FindManyRangeCore(secondaryIndex0, secondaryIndex0Selector, System.Collections.Generic.Comparer<uint>.Default, min, max, ascendant);
        }


        void ITableUniqueValidate.ValidateUnique(ValidateResult resultSet)
        {
#if !DISABLE_MASTERMEMORY_VALIDATOR

            ValidateUniqueCore(data, primaryIndexSelector, "(SkillSetId, SkillId)", resultSet);       

#endif
        }

#if !DISABLE_MASTERMEMORY_METADATABASE

        public static MasterMemory.Meta.MetaTable CreateMetaTable()
        {
            return new MasterMemory.Meta.MetaTable(typeof(EnemySkillSetEntity), typeof(EnemySkillSetTable), "EnemySkillSet",
                new MasterMemory.Meta.MetaProperty[]
                {
                    new MasterMemory.Meta.MetaProperty(typeof(EnemySkillSetEntity).GetProperty("SkillSetId")),
                    new MasterMemory.Meta.MetaProperty(typeof(EnemySkillSetEntity).GetProperty("SkillId")),
                },
                new MasterMemory.Meta.MetaIndex[]{
                    new MasterMemory.Meta.MetaIndex(new System.Reflection.PropertyInfo[] {
                        typeof(EnemySkillSetEntity).GetProperty("SkillSetId"),
                        typeof(EnemySkillSetEntity).GetProperty("SkillId"),
                    }, true, true, System.Collections.Generic.Comparer<(uint SkillSetId, uint SkillId)>.Default),
                    new MasterMemory.Meta.MetaIndex(new System.Reflection.PropertyInfo[] {
                        typeof(EnemySkillSetEntity).GetProperty("SkillSetId"),
                    }, false, false, System.Collections.Generic.Comparer<uint>.Default),
                });
        }

#endif
    }
}